LetsEat/Models/ErrorViewModel.cs
namespace LetsEat.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

LetsEat/Models/Restaurant.cs
using System;

namespace LetsEat.Models
{
	public class Restaurant
	{
		public Restaurant()
		{
		}

		public string APIResponse { get; set; }
		public long RestID { get; set; }
		public string Name { get; set; }
		public string CuisineType { get; set; }
		public string Address { get; set; }
		public string City { get; set; }
		public string State { get; set; }

	}
}

LetsEat/Controllers/FavoriteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LetsEat.Models;
using Microsoft.AspNetCore.Mvc;

namespace LetsEat.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly IFavoriteRepo repo;

        public FavoriteController(IFavoriteRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            var favorites = repo.GetAllFavorites();
            return View(favorites);
        }

        public IActionResult InsertFavorite(long id)
        {
            var favorite = repo.GetRestaurant(id);

            repo.InsertFavorite(favorite);
            return RedirectToAction("Index");
        }

        //public IActionResult ViewFavorite(string name)
        //{
        //    var favorite = repo.GetFavorite(name);
        //    return View(favorite);
        //}

        public IActionResult DeleteFavorite(long id)
        {
            repo.DeleteFavorite(id);
            return RedirectToAction("Index");
        }
    }
}

LetsEat/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using LetsEat.Models;

namespace LetsEat.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

LetsEat/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LetsEat.Models;
using Microsoft.AspNetCore.Mvc;

namespace LetsEat.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly IRestaurantRepo repo;

        public RestaurantController(IRestaurantRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult Index(string zipCode)
        {
            var restaurantList = new List<Restaurant>();

            if (zipCode == null)
            {
                return View(restaurantList);
            }
            try
            {
                restaurantList = repo.GetAPIResponse(zipCode).ToList();
            }
            catch (AggregateException)
            {
                return RedirectToAction("Index", "Restaurant");
            }
            return View(restaurantList);
        }

        // no elements in sequence, come back to it
        // public IActionResult ViewRestaurant(long restID)
        //{
        //    var restaurant = new Restaurant();
        //    try
        //    {
        //        restaurant = repo.GetRestaurant(restID);
        //    }
        //    catch (AggregateException)
        //    {
        //        return RedirectToAction("Index", "Restaurant");
        //    }

        //    return View(restaurant);
        //}
    }
}

LetsEat/Views/Favorite/Index.cshtml
@model List<Restaurant>

<h2>Favorites</h2>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Cuisine Type</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Action</th>
    </tr>

    @foreach (var favorite in @Model)
    {
        <tr>
            <td>@favorite.RestID</td>
            <td>@favorite.Name</td>
            <td>@favorite.CuisineType</td>
            <td>@favorite.Address</td>
            <td>@favorite.City</td>
            <td>@favorite.State</td>
            <td><a href=/Favorite/DeleteFavorite/@favorite.RestID>Remove from Favorites</a></td>
        </tr>
    }
</table>

<div style="width: 20%; margin: 0 auto" class="text-center">
    <div>
        <input type="button" value="Return to Home" onclick="window.location.href='@Url.Action("Index", "Home" )';" />
    </div>
</div>

LetsEat/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}

<div class="text-center">
    <h1 class="display-4">Welcome to LetSeat (Say it out loud)</h1>
    <p> Here we generate restaurants in your area!</p>
    <p> Head over to the Restaurants tab to get started.</p>   
</div>

LetsEat/Views/Restaurant/Index.cshtml
@model List<Restaurant>

<h2>Restaurants</h2>

<div class="text-center">
    <h1 class="display-4">Generate Restaurants</h1>
    <p>Enter your zipcode below to get restaurants in your area.</p>
</div>


<div style="width: 20%; margin: 0 auto" class="text-center">
    <div class="form-row align-items-center">
        @using (Html.BeginForm("Index", "Restaurant", FormMethod.Get))
            {
            <div class="form-group">
                <input type="text" name="zipCode" class="form-control text-center" maxlength="5" />
            </div>
            <br />

            <input type="submit" value="Enter" class="btn btn-primary"/>
            }
    </div>
</div>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Cuisine Type</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Action</th>
    </tr>

    @foreach (var restaurant in Model)
    {
        <tr>
            <td>@restaurant.RestID</td>
            @*<td><a href=/Restaurant/ViewRestaurant/@restaurant.RestID>@restaurant.RestID</a></td>*@
            <td>@restaurant.Name</td>
            <td>@restaurant.CuisineType</td>
            <td>@restaurant.Address</td>
            <td>@restaurant.City</td>
            <td>@restaurant.State</td>
            <td><a href=/Favorite/InsertFavorite/@restaurant.RestID>Add to Favorites</a></td>
        </tr>
    }
</table>

<div style="width: 20%; margin: 0 auto" class="text-center">
    <div>
        <input type="button" value="Return to Home" onclick="window.location.href='@Url.Action("Index", "Home" )';" />
    </div>
</div>

LetsEat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LetSeat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LetsEat.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Restaurant" asp-action="Index">LetSeat!</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favorite" asp-action="Index">Favorites</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LetSeat! - Nolan Martin <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>